# -*- coding: utf-8 -*-
"""AI_RAG_AGENT_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/161hdq_TmxkTNwQMhdEjYX5JdFqZDxHj1
"""

!pip install requests==2.32.4 --force-reinstall --quiet

!pip install -q langchain langchain-community sentence-transformers faiss-cpu pypdf

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Embeddings loaded successfully")

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/Adith John Resume Updated.pdf")
documents = loader.load()

print(len(documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

docs = text_splitter.split_documents(documents)

print(len(docs))

from langchain_community.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(docs, embeddings)

query = "What is this document about?"

results = vectorstore.similarity_search(query, k=3)

for r in results:
    print(r.page_content)
    print("------")